version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fisher_fans
    ports:
      - "3306:3306"
    networks:
      - fisher_fans_network
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - fisher_fans_network
    depends_on:
      - db

  api:
    build: .
    container_name: fisher_fans_api
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: fisher_fans
    ports:
      - "8000:8000"
    networks:
      - fisher_fans_network
    depends_on:
      - db
    volumes:
      - .:/app
      - ./data:/app/data

  test:
    build: .
    container_name: fisher_fans_api_test
    command: ["pytest", "tests"]
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: fisher_fans
    networks:
      - fisher_fans_network
    depends_on:
      - db
    volumes:
      - .:/app
      - ./data:/app/data

volumes:
  db_data:

networks:
  fisher_fans_network:
    driver: bridge